import React from 'react';
import { DocumentAnalysis } from '../types/legal';
import {
  FileText,
  Printer,
  Copy,
  Check,
  Scale,
  ShieldCheck,
  Calendar,
  DollarSign,
  AlertTriangle,
  HelpCircle,
} from 'lucide-react';

interface ReportViewProps {
  analysis: DocumentAnalysis;
}

export const ReportView: React.FC<ReportViewProps> = ({ analysis }) => {
  const [copied, setCopied] = React.useState(false);

  const handlePrint = () => {
    window.print();
  };

  const handleCopy = () => {
    const text = `LEGAL INTELLIGENCE BRIEF
Generated by LEGALENS AI
Document: ${analysis.overview.title}
Parties: ${analysis.overview.parties.join(' vs ')}
Effective Date: ${analysis.overview.effectiveDate || 'N/A'}
Jurisdiction: ${analysis.overview.jurisdiction || 'N/A'}

EXECUTIVE SUMMARY:
${analysis.executiveSummary.whatThisIs}
Financial Commitments: ${analysis.executiveSummary.financialSummary}
Duration & Term: ${analysis.executiveSummary.durationAndTerm}
Termination: ${analysis.executiveSummary.howTerminationWorks}
Failure Consequences: ${analysis.executiveSummary.failureConsequences}
Review Items: ${analysis.executiveSummary.keyThingsToReview}

TOP ATTENTION ITEMS:
${analysis.attentionItems.map((a, i) => `${i + 1}. [${a.attentionLevel}] ${a.title}\nIssue: ${a.detectedIssue}\nWhat to clarify: ${a.whatUserShouldClarify}\n`).join('\n')}

QUESTIONS FOR COUNSEL:
${analysis.lawyerQuestions.map((q, i) => `${i + 1}. ${q.question} (${q.priority} Priority)\nRationale: ${q.rationale}\n`).join('\n')}

DISCLAIMER:
This report is provided for informational and educational assistance only. Legalens AI does not provide legal advice.`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="p-6 space-y-6 max-w-5xl mx-auto w-full">
      {/* Top Controls (Hidden during print) */}
      <div className="no-print flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h2 className="text-xl font-bold tracking-tight text-slate-900 flex items-center gap-2">
            <FileText className="h-5 w-5 text-indigo-700" />
            <span>Formal Legal Intelligence Brief</span>
          </h2>
          <p className="text-xs text-slate-500 mt-1">
            Complete structured executive dossier ready for printing, PDF archiving, or sharing with an attorney.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 rounded-xl border border-slate-200 bg-white px-4 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50 shadow-sm"
          >
            {copied ? <Check className="h-3.5 w-3.5 text-emerald-600" /> : <Copy className="h-3.5 w-3.5" />}
            <span>{copied ? 'Copied' : 'Copy Text'}</span>
          </button>

          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 rounded-xl bg-indigo-950 px-5 py-2 text-xs font-semibold text-white shadow-sm hover:bg-indigo-900 transition"
          >
            <Printer className="h-3.5 w-3.5" />
            <span>Print / Save as PDF</span>
          </button>
        </div>
      </div>

      {/* PRINTABLE DOSSIER SHEET */}
      <div className="rounded-2xl border border-slate-300 bg-white p-10 shadow-md space-y-8 font-sans text-slate-900 print:border-none print:shadow-none print:p-0">
        {/* Document Header */}
        <div className="border-b-2 border-slate-900 pb-6">
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-extrabold uppercase tracking-widest text-indigo-900">
              LEGALENS AI • LEGAL INTELLIGENCE BRIEF
            </span>
            <span className="text-xs text-slate-500 font-mono">
              Date: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
            </span>
          </div>

          <h1 className="text-2xl font-bold text-slate-950 mt-3">
            {analysis.overview.title}
          </h1>

          <div className="mt-3 grid grid-cols-2 gap-4 text-xs sm:grid-cols-4 bg-slate-50 p-4 rounded-xl border border-slate-200">
            <div>
              <span className="font-semibold text-slate-500 block">Document Type</span>
              <span className="font-bold text-slate-900 mt-0.5 block">{analysis.overview.type}</span>
            </div>
            <div>
              <span className="font-semibold text-slate-500 block">Parties Involved</span>
              <span className="font-bold text-slate-900 mt-0.5 block">{analysis.overview.parties.join(', ')}</span>
            </div>
            <div>
              <span className="font-semibold text-slate-500 block">Jurisdiction</span>
              <span className="font-bold text-slate-900 mt-0.5 block">{analysis.overview.jurisdiction || 'General / Unstated'}</span>
            </div>
            <div>
              <span className="font-semibold text-slate-500 block">Term / Expiration</span>
              <span className="font-bold text-slate-900 mt-0.5 block">
                {analysis.overview.effectiveDate || 'Execution'} &rarr; {analysis.overview.expiryDate || 'Open'}
              </span>
            </div>
          </div>
        </div>

        {/* Section 1: Executive Plain-Language Summary */}
        <div className="space-y-3 print-break-inside-avoid">
          <h3 className="text-sm font-bold uppercase tracking-wider text-slate-900 border-b border-slate-200 pb-1.5">
            1. Executive Plain-Language Summary
          </h3>
          <p className="text-xs leading-relaxed text-slate-800">
            {analysis.executiveSummary.whatThisIs}
          </p>

          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 text-xs">
            <div className="rounded-lg border border-slate-200 p-3 bg-slate-50/60">
              <span className="font-bold block mb-1">Financial Obligations:</span>
              <p className="text-slate-700">{analysis.executiveSummary.financialSummary}</p>
            </div>
            <div className="rounded-lg border border-slate-200 p-3 bg-slate-50/60">
              <span className="font-bold block mb-1">Termination & Defaults:</span>
              <p className="text-slate-700">{analysis.executiveSummary.howTerminationWorks}</p>
            </div>
          </div>
        </div>

        {/* Section 2: Review Radar & Potential Friction */}
        <div className="space-y-3 print-break-inside-avoid">
          <h3 className="text-sm font-bold uppercase tracking-wider text-slate-900 border-b border-slate-200 pb-1.5">
            2. Areas Requiring Review & Clarification
          </h3>
          <div className="space-y-3">
            {analysis.attentionItems.map((item) => (
              <div key={item.id} className="border-l-2 border-amber-500 pl-3 py-1 space-y-1 text-xs">
                <div className="flex items-center justify-between">
                  <span className="font-bold text-slate-900">{item.title}</span>
                  <span className="font-mono text-[10px] text-slate-500">{item.evidence.section}</span>
                </div>
                <p className="text-slate-700">{item.detectedIssue}</p>
                <p className="text-slate-600 italic">
                  <strong className="font-semibold text-slate-800">What to clarify:</strong> {item.whatUserShouldClarify}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Section 3: Inconsistencies & Contradictions */}
        {analysis.inconsistencies.length > 0 && (
          <div className="space-y-3 print-break-inside-avoid">
            <h3 className="text-sm font-bold uppercase tracking-wider text-rose-800 border-b border-rose-200 pb-1.5">
              3. Internal Contradictions Detected
            </h3>
            {analysis.inconsistencies.map((inc) => (
              <div key={inc.id} className="rounded-xl border border-rose-200 p-3 text-xs space-y-2 bg-rose-50/30">
                <span className="font-bold text-rose-950 block">{inc.title}</span>
                <p className="text-slate-700">{inc.whyInconsistent}</p>
                <div className="text-slate-600 font-medium">
                  <strong>Recommendation:</strong> {inc.recommendation}
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Section 4: Questions to Ask Legal Counsel */}
        <div className="space-y-3 print-break-inside-avoid">
          <h3 className="text-sm font-bold uppercase tracking-wider text-slate-900 border-b border-slate-200 pb-1.5">
            4. Recommended Questions for Legal Counsel
          </h3>
          <div className="space-y-2 text-xs">
            {analysis.lawyerQuestions.map((q, i) => (
              <div key={q.id} className="flex items-start gap-2">
                <span className="font-bold text-indigo-900 shrink-0">{i + 1}.</span>
                <div>
                  <span className="font-bold text-slate-900">{q.question}</span>
                  <span className="text-slate-500 block text-[11px]">
                    Rationale: {q.rationale} ({q.relatedSection})
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Section 5: Legal Safety Statement */}
        <div className="border-t-2 border-slate-200 pt-6 text-[11px] text-slate-500 leading-relaxed print-break-inside-avoid">
          <div className="flex items-center gap-1.5 font-bold text-slate-800 mb-1">
            <ShieldCheck className="h-4 w-4 text-indigo-600" />
            <span>Important Legal Notice</span>
          </div>
          <p>
            This document is an informational legal brief generated by LEGALENS AI to assist users in understanding, navigating, and preparing for consultations regarding their legal documents. This document does not constitute legal advice, does not establish an attorney-client relationship, and cannot replace the counsel of a licensed attorney.
          </p>
        </div>
      </div>
    </div>
  );
};
